"""initial database configuration

Revision ID: f4ab71ad4e11
Revises: 
Create Date: 2020-11-14 16:02:44.534787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ab71ad4e11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('volume', sa.REAL(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_crops_recent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('volume', sa.REAL(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_fish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('volume', sa.REAL(), nullable=True),
    sa.Column('min_price', sa.REAL(), nullable=True),
    sa.Column('max_price', sa.REAL(), nullable=True),
    sa.Column('frequent_price', sa.REAL(), nullable=True),
    sa.Column('average_price', sa.REAL(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_fish_recent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('volume', sa.REAL(), nullable=True),
    sa.Column('min_price', sa.REAL(), nullable=True),
    sa.Column('max_price', sa.REAL(), nullable=True),
    sa.Column('frequent_price', sa.REAL(), nullable=True),
    sa.Column('average_price', sa.REAL(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('volume', sa.REAL(), nullable=True),
    sa.Column('min', sa.REAL(), nullable=True),
    sa.Column('max', sa.REAL(), nullable=True),
    sa.Column('mode', sa.REAL(), nullable=True),
    sa.Column('mean', sa.REAL(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_crops_recent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('volume', sa.REAL(), nullable=True),
    sa.Column('min', sa.REAL(), nullable=True),
    sa.Column('max', sa.REAL(), nullable=True),
    sa.Column('mode', sa.REAL(), nullable=True),
    sa.Column('mean', sa.REAL(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_crops_recent')
    op.drop_table('monthly_crops')
    op.drop_table('daily_fish_recent')
    op.drop_table('daily_fish')
    op.drop_table('daily_crops_recent')
    op.drop_table('daily_crops')
    # ### end Alembic commands ###
